In [28]:
import torch
import numpy as np

In [3]:
torch.version.__version__

'1.3.1+cpu'

In [36]:
x = np.array([1, 2, 34, 5])
x

array([ 1,  2, 34,  5])

In [38]:
torch.is_tensor(x)

False

In [6]:
torch.is_storage(x)

False

In [39]:
a = torch.randn((2,3), dtype=torch.float32)
a

tensor([[ 0.0412, -0.8621, -1.3947],
        [-0.1813, -0.8332, -0.8656]])

In [21]:
torch.numel(a)

6

In [22]:
torch.is_storage(a)

False

In [25]:
b = torch.eye(5,5)
b

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [41]:
torch.from_numpy(x)

tensor([ 1,  2, 34,  5])

In [42]:
d = torch.randn(4,5)
d

tensor([[-1.6583, -0.4947,  1.1452, -0.1542,  2.1103],
        [ 0.1779, -0.0139,  0.6374, -0.0153, -0.3377],
        [ 0.0682,  1.5135, -2.2416,  0.9912, -0.4521],
        [ 0.2138, -0.2214,  0.5172, -0.7485,  2.5323]])

In [44]:
torch.argmax(d, dim=1, keepdims=True)

tensor([[4],
        [2],
        [1],
        [4]])

In [48]:
print(torch.max(d, dim=1).values)
print(torch.max(d, dim=1).indices)

tensor([2.1103, 0.6374, 1.5135, 2.5323])
tensor([4, 2, 1, 4])


In [53]:
c = torch.cat((d, d), axis=0)
c

tensor([[-1.6583, -0.4947,  1.1452, -0.1542,  2.1103],
        [ 0.1779, -0.0139,  0.6374, -0.0153, -0.3377],
        [ 0.0682,  1.5135, -2.2416,  0.9912, -0.4521],
        [ 0.2138, -0.2214,  0.5172, -0.7485,  2.5323],
        [-1.6583, -0.4947,  1.1452, -0.1542,  2.1103],
        [ 0.1779, -0.0139,  0.6374, -0.0153, -0.3377],
        [ 0.0682,  1.5135, -2.2416,  0.9912, -0.4521],
        [ 0.2138, -0.2214,  0.5172, -0.7485,  2.5323]])

In [55]:
torch.chunk(c, 3)

(tensor([[-1.6583, -0.4947,  1.1452, -0.1542,  2.1103],
         [ 0.1779, -0.0139,  0.6374, -0.0153, -0.3377],
         [ 0.0682,  1.5135, -2.2416,  0.9912, -0.4521]]),
 tensor([[ 0.2138, -0.2214,  0.5172, -0.7485,  2.5323],
         [-1.6583, -0.4947,  1.1452, -0.1542,  2.1103],
         [ 0.1779, -0.0139,  0.6374, -0.0153, -0.3377]]),
 tensor([[ 0.0682,  1.5135, -2.2416,  0.9912, -0.4521],
         [ 0.2138, -0.2214,  0.5172, -0.7485,  2.5323]]))

In [59]:
f = torch.Tensor([[2, 4],
              [5, 6]])
f

tensor([[2., 4.],
        [5., 6.]])

In [61]:
torch.gather()

True

In [67]:
t = torch.tensor([[1,2],[3,4]])
torch.gather(t, 1, torch.LongTensor([[0,0],[1,1]]))
#     tensor([[ 1,  1],
#             [ 4,  3]])

tensor([[1, 1],
        [4, 4]])

In [66]:
torch.LongTensor([[2, 4],
                 [5, 6]])

tensor([[2, 4],
        [5, 6]])

In [68]:
t.numpy()

array([[1, 2],
       [3, 4]])

In [79]:
torch.LongTensor([5.,00])

tensor([5, 0])

In [80]:
d

tensor([[-1.6583, -0.4947,  1.1452, -0.1542,  2.1103],
        [ 0.1779, -0.0139,  0.6374, -0.0153, -0.3377],
        [ 0.0682,  1.5135, -2.2416,  0.9912, -0.4521],
        [ 0.2138, -0.2214,  0.5172, -0.7485,  2.5323]])

In [82]:
d.t()

tensor([[-1.6583,  0.1779,  0.0682,  0.2138],
        [-0.4947, -0.0139,  1.5135, -0.2214],
        [ 1.1452,  0.6374, -2.2416,  0.5172],
        [-0.1542, -0.0153,  0.9912, -0.7485],
        [ 2.1103, -0.3377, -0.4521,  2.5323]])

In [93]:
d.transpose(1, 1) == d.transpose(0, 0)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [104]:
f = torch.unbind(d, 0)
f

(tensor([-1.6583, -0.4947,  1.1452, -0.1542,  2.1103]),
 tensor([ 0.1779, -0.0139,  0.6374, -0.0153, -0.3377]),
 tensor([ 0.0682,  1.5135, -2.2416,  0.9912, -0.4521]),
 tensor([ 0.2138, -0.2214,  0.5172, -0.7485,  2.5323]))

In [106]:
[i.numpy() for i in f]

[array([-1.6582645 , -0.4946629 ,  1.1452267 , -0.15424214,  2.110283  ],
       dtype=float32),
 array([ 0.17785655, -0.01392853,  0.6373539 , -0.01525345, -0.33765766],
       dtype=float32),
 array([ 0.06821612,  1.5135193 , -2.2416096 ,  0.99123174, -0.45205608],
       dtype=float32),
 array([ 0.21382846, -0.22142047,  0.5171621 , -0.7484755 ,  2.532313  ],
       dtype=float32)]

In [111]:
torch.mul(d, 10)

tensor([[-16.5826,  -4.9466,  11.4523,  -1.5424,  21.1028],
        [  1.7786,  -0.1393,   6.3735,  -0.1525,  -3.3766],
        [  0.6822,  15.1352, -22.4161,   9.9123,  -4.5206],
        [  2.1383,  -2.2142,   5.1716,  -7.4848,  25.3231]])

In [114]:
torch.manual_seed(1234)
xy = torch.randn(5,5)
xy

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0831, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.4949,  1.4778, -0.1696, -0.9919],
        [-1.4569,  0.2563, -0.4030,  0.4195,  0.9380]])

In [115]:
torch.floor(xy)

tensor([[-1., -1.,  0., -1.,  0.],
        [ 0., -1., -1., -1., -1.],
        [-2., -1.,  0., -1.,  1.],
        [ 0., -2.,  1., -1., -1.],
        [-2.,  0., -1.,  0.,  0.]])

In [119]:
torch.clamp(xy, min=-1)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0000, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.0000,  1.4778, -0.1696, -0.9919],
        [-1.0000,  0.2563, -0.4030,  0.4195,  0.9380]])

In [123]:
exp_xy = torch.exp(xy)

In [122]:
torch.frac(torch.exp(xy))

tensor([[0.8943, 0.6086, 0.1771, 0.4141, 0.0554],
        [0.9511, 0.9421, 0.6266, 0.8063, 0.4896],
        [0.3385, 0.5742, 0.6424, 0.5975, 0.1600],
        [0.2226, 0.2243, 0.3832, 0.8440, 0.3709],
        [0.2330, 0.2921, 0.6683, 0.5212, 0.5549]])

In [124]:
torch.sigmoid(exp_xy, )

tensor([[0.7098, 0.6476, 0.7644, 0.6021, 0.7418],
        [0.8756, 0.7195, 0.6517, 0.6913, 0.6200],
        [0.5838, 0.6397, 0.9335, 0.6451, 0.9846],
        [0.9023, 0.5558, 0.9877, 0.6993, 0.5917],
        [0.5580, 0.7845, 0.6611, 0.8207, 0.9279]])

In [125]:
torch.sqrt(exp_xy)

tensor([[0.9457, 0.7801, 1.0850, 0.6435, 1.0273],
        [1.3968, 0.9706, 0.7916, 0.8980, 0.6997],
        [0.5818, 0.7578, 1.6255, 0.7730, 2.0396],
        [1.4908, 0.4736, 2.0936, 0.9187, 0.6090],
        [0.4827, 1.1367, 0.8175, 1.2334, 1.5984]])

In [127]:
torch.manual_seed(1234)
torch.randn(4,4)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817],
        [ 0.0539,  0.6684, -0.0597, -0.4675],
        [-0.2153,  0.8840, -0.7584, -0.3689],
        [-0.3424, -1.4020,  0.3206, -1.0219]])

In [128]:
torch.rand(4,4)

tensor([[0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294],
        [0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343]])

In [140]:
torch.manual_seed(1234)
torch.Tensor(4, 4).uniform_(0, 1)

tensor([[0.0290, 0.4019, 0.2598, 0.3666],
        [0.0583, 0.7006, 0.0518, 0.4681],
        [0.6738, 0.3315, 0.7837, 0.5631],
        [0.7749, 0.8208, 0.2793, 0.6817]])

In [160]:
# Bernoulli Sampling
samp = torch.distributions.Bernoulli(torch.Tensor([0.63]))
# 0.63 % chance to be True
samp

Bernoulli(probs: tensor([0.6300]))

In [161]:
for _ in range(10):
    print(samp.sample())

tensor([0.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])


In [168]:
torch.bernoulli(torch.Tensor([0.69]))

tensor([1.])

In [174]:
torch.normal(mean=0.5, std=torch.tensor([0.05]))

tensor([0.5440])

Autograd

In [187]:
torch.ones(3, 3, requires_grad=True)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [208]:
# Using forward pass
def forward(x):
    return x * w

x_data = torch.tensor([11.0, 14.0, 33.0])
y_data = torch.tensor([21.0, 22.0, 64.0])

w = torch.tensor([1.0], requires_grad=True)

# Before training
print("predict (before training)", 4, forward(4))

predict (before training) 4 tensor([4.], grad_fn=<MulBackward0>)


In [209]:
w.requires_grad

True

In [210]:
# define the loss function
def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y)*(y_pred - y)

In [212]:
# Run the training Loop
for epoch in range(10):
    for x_val, y_val in zip(x_data, y_data):
        l = loss(x_val, y_val)
        l.backward()
        print("\tgrad: ", x_val, y_val, w.grad.data[0])
        w.data = w.data - 0.0001 * w.grad.data
        
        # Manually set the gradients to zero after updating weights
        w.grad.data.zero_()
    
    print("progress:", epoch, l.data[0])

	grad:  tensor(11.) tensor(21.) tensor(-6.7247e+21)
	grad:  tensor(14.) tensor(22.) tensor(-1.0629e+22)
	grad:  tensor(33.) tensor(64.) tensor(-5.6743e+22)
progress: 0 tensor(inf)
	grad:  tensor(11.) tensor(21.) tensor(-4.9316e+21)
	grad:  tensor(14.) tensor(22.) tensor(-7.7950e+21)
	grad:  tensor(33.) tensor(64.) tensor(-4.1612e+22)
progress: 1 tensor(inf)
	grad:  tensor(11.) tensor(21.) tensor(-3.6166e+21)
	grad:  tensor(14.) tensor(22.) tensor(-5.7165e+21)
	grad:  tensor(33.) tensor(64.) tensor(-3.0516e+22)
progress: 2 tensor(inf)
	grad:  tensor(11.) tensor(21.) tensor(-2.6522e+21)
	grad:  tensor(14.) tensor(22.) tensor(-4.1922e+21)
	grad:  tensor(33.) tensor(64.) tensor(-2.2379e+22)
progress: 3 tensor(inf)
	grad:  tensor(11.) tensor(21.) tensor(-1.9450e+21)
	grad:  tensor(14.) tensor(22.) tensor(-3.0743e+21)
	grad:  tensor(33.) tensor(64.) tensor(-1.6412e+22)
progress: 4 tensor(inf)
	grad:  tensor(11.) tensor(21.) tensor(-1.4264e+21)
	grad:  tensor(14.) tensor(22.) tensor(-2.2546e+

In [194]:
# Creating the graph
x = torch.tensor(1.0, requires_grad = True)
y = torch.tensor(2.0)
z = x * y

# Displaying
for i, name in zip([x, y, z], "xyz"):
    print(f"{name}\ndata: {i.data}\nrequires_grad: {i.requires_grad}\n\
grad: {i.grad}\ngrad_fn: {i.grad_fn}\nis_leaf: {i.is_leaf}\n")

x
data: 1.0
requires_grad: True
grad: None
grad_fn: None
is_leaf: True

y
data: 2.0
requires_grad: False
grad: None
grad_fn: None
is_leaf: True

z
data: 2.0
requires_grad: True
grad: None
grad_fn: <MulBackward0 object at 0x7f1a14432550>
is_leaf: False



In [218]:
a = torch.tensor([5.])

weights = [torch.tensor([i], requires_grad=True) for i in (12., 53., 91., 73.)]

w1, w2, w3, w4 = weights

b = w1 * a
c = w2 * a
d = w3 * b + w4 * c
Loss = (10 - d)

Loss.backward()

In [219]:
for index, weight in enumerate(weights, start=1):
    gradient, *_ = weight.grad.data
    print(f"Gradient of w{index} w.r.t Loss: {gradient}")

Gradient of w1 w.r.t Loss: -455.0
Gradient of w2 w.r.t Loss: -365.0
Gradient of w3 w.r.t Loss: -60.0
Gradient of w4 w.r.t Loss: -265.0
